name: Build and Deploy Backend

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # -----------------------------
    # TEST SSH
    # -----------------------------
    - name: Test SSH connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "SSH OK"

    # -----------------------------
    # Set up Java
    # -----------------------------
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # -----------------------------
    # Build backend
    # -----------------------------
    - name: Build backend without tests
      run: |
        ./mvnw -DskipTests package

    # -----------------------------
    # Login GHCR
    # -----------------------------
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # -----------------------------
    # Build and push Docker image
    # -----------------------------
    - name: Build and Push
      run: |
        docker build -t ghcr.io/cesarcanro1/proyecto-backend:latest .
        docker push ghcr.io/cesarcanro1/proyecto-backend:latest

    # -----------------------------
    # Deploy to MicroK8s
    # -----------------------------
    - name: Deploy to MicroK8s
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Actualizando imagen..."
          sudo microk8s kubectl -n proyecto-web set image deployment/backend backend=ghcr.io/cesarcanro1/proyecto-backend:latest
          sudo microk8s kubectl -n proyecto-web rollout restart deployment backend
          sudo microk8s kubectl -n proyecto-web rollout status deployment backend --timeout=60s
